language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install -r REQUIREMENTS2; fi
  - if [[ ${TRAVIS_PYTHON_VERSION%.?} == 3 ]]; then pip install -r REQUIREMENTS; fi
  - then pip install -r REQUIREMENTS-ADDITIONAL
  - "python setup_travis.py install"
# command to run tests
script: nosetests
services:
  - redis-server
